<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwfFqPQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwfFqPQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFwfFqPQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFwfFqPQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFwfFqPQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FwfFqPQ',
    'container.build_id' => '1041c80c',
    'container.build_time' => 1564395964,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwfFqPQ');
