<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2qfSd4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2qfSd4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2qfSd4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2qfSd4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF2qfSd4\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F2qfSd4',
    'container.build_id' => 'b875775c',
    'container.build_time' => 1564338121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2qfSd4');
