<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPAV3eQI\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPAV3eQI/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPAV3eQI.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPAV3eQI\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPAV3eQI\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PAV3eQI',
    'container.build_id' => 'c79c67d3',
    'container.build_time' => 1564346055,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPAV3eQI');
